import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';

export async function POST(request: NextRequest) {
  try {
    const projectData = await request.json();

    const apiKey = process.env.ANTHROPIC_API_KEY;
    const companyName = projectData.deckAnalysis?.elements?.companyName?.content || 'Company';

    // Build spec document
    const buildSpecMarkdown = () => {
      const { brandVoice, designDirection, siteStructure, homepageContent, websitePurpose } = projectData;

      return `# Website Specification Document
## ${companyName}

---

## 1. PROJECT OVERVIEW

**Company Name:** ${companyName}
**Tagline:** ${projectData.deckAnalysis?.elements?.tagline?.content || 'TBD'}
**One-liner:** ${brandVoice?.oneLiner || 'TBD'}

**Primary Website Goal:** Attract investors, talent, and early partners
**Target Audience:**
1. Investors (primary)
2. Talent / potential hires
3. Early partners and collaborators

**Company Stage:** ${websitePurpose?.companyStage || 'Building'}

---

## 2. BRAND GUIDELINES

**Brand Personality:** ${brandVoice?.personalityTraits?.join(', ') || 'Professional, Innovative'}

**Tone of Voice:** ${brandVoice?.desiredFeeling || 'Credible, exciting, breakthrough'}

**Color Palette:**
- Primary: ${designDirection?.colorPalette?.primary || '#1e3a5f'}
- Accent: ${designDirection?.colorPalette?.accent || '#3b82f6'}
- Background: ${designDirection?.colorPalette?.background || '#ffffff'}
- Text: ${designDirection?.colorPalette?.text || '#1f2937'}

**Typography:**
- Headings: ${designDirection?.typography?.headingFont || 'Inter'}
- Body: ${designDirection?.typography?.bodyFont || 'Inter'}

**Imagery Style:** ${designDirection?.imageryStyle || 'Abstract scientific visuals, avoid generic stock photos'}

---

## 3. SITE STRUCTURE

**Type:** ${siteStructure?.type || 'Single-page'}

**Sections:** ${siteStructure?.sections?.join(' → ') || 'Home → About → Technology → Team → Contact'}

**Navigation Items:** ${siteStructure?.navigationItems?.join(', ') || 'About, Technology, Team, Contact'}

**Footer Contents:** ${siteStructure?.footerItems?.join(', ') || 'Privacy Policy, LinkedIn, Email'}

---

## 4. PAGE CONTENT

### Hero Section
**Headline:** ${homepageContent?.hero?.headline || 'TBD'}
**Subheadline:** ${homepageContent?.hero?.subheadline || 'TBD'}
**Primary CTA:** ${homepageContent?.hero?.primaryCTA || 'Contact Us'}

### Problem Section
**Header:** ${homepageContent?.problem?.header || 'The Challenge'}
**Body:** ${homepageContent?.problem?.body || 'TBD'}

### Solution Section
**Header:** ${homepageContent?.solution?.header || 'Our Solution'}
**Body:** ${homepageContent?.solution?.body || 'TBD'}

### Benefits
${homepageContent?.benefits?.map((b: { headline: string; description: string }, i: number) =>
  `${i + 1}. **${b.headline}:** ${b.description}`
).join('\n') || '- TBD'}

### How It Works
${homepageContent?.howItWorks?.map((s: { step: number; title: string; description: string }) =>
  `${s.step}. **${s.title}:** ${s.description}`
).join('\n') || '- TBD'}

### Final CTA
**Headline:** ${homepageContent?.finalCTA?.headline || 'Ready to Get Started?'}
**Button Text:** ${homepageContent?.finalCTA?.buttonText || 'Contact Us'}
**Supporting Text:** ${homepageContent?.finalCTA?.supportingText || ''}

---

## 5. DESIGN NOTES

**Reference Websites:**
${designDirection?.referenceWebsites?.map((url: string) => `- ${url}`).join('\n') || '- TBD'}

**What to Avoid:**
${designDirection?.avoidList?.map((item: string) => `- ${item}`).join('\n') || '- Generic stock photos'}

**Trust Signals to Include:**
${designDirection?.trustSignals?.map((item: string) => `- ${item}`).join('\n') || '- Team credentials\n- University affiliations'}

---

## 6. TECHNICAL REQUIREMENTS

- Contact form with email notification
- Google Analytics integration
- Mobile-responsive design
- Fast loading (< 3 seconds)
- SEO meta tags

**Social Links:**
- LinkedIn: ${websitePurpose?.linkedInUrl || 'TBD'}
- Twitter/X: ${websitePurpose?.twitterUrl || 'TBD'}

---

## 7. ASSETS NEEDED

- [ ] Company logo (SVG preferred)
- [ ] Favicon
- [ ] Team headshots
- [ ] Product/technology images or diagrams
- [ ] Partner/investor logos (if applicable)
- [ ] Background images or abstract visuals

---

*Generated by Pitch to Site*
`;
    };

    if (!apiKey || apiKey === 'your_api_key_here') {
      return NextResponse.json({ markdown: buildSpecMarkdown() });
    }

    // With API key, we can enhance the spec
    const client = new Anthropic({ apiKey });

    const prompt = `Please compile everything we've created into a single Website Specification Document. Review and enhance this document, keeping the same structure but improving clarity and adding any missing details based on best practices for Tough Tech startup websites.

${buildSpecMarkdown()}

Format it cleanly so I could hand it directly to a developer. Return the improved markdown document.`;

    const message = await client.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 4096,
      messages: [{ role: 'user', content: prompt }],
    });

    const responseText = message.content[0].type === 'text' ? message.content[0].text : buildSpecMarkdown();

    return NextResponse.json({ markdown: responseText });
  } catch (error) {
    console.error('Generate spec error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to generate spec' },
      { status: 500 }
    );
  }
}
